# Generated by Django 4.2.9 on 2024-02-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_similar_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
